### ISSUE TITLE
jquery CDN

### ISSUE THREAD

**Issue by snowsandpatrol** [jeremiahalex/wdi-sg-3#27]
what is the difference in pulling jquery from different CDNs?

src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script type='text/javascript' src="./jqueryexercise.js"></script>

<script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>

**Comment by jeremiahalex** [comment]
Most of the big ones should have similar reliability. There could be speed differences based on server locations much like hosting a website but I wouldn't worry too much about. Someone told me that the Google CDNs don't work in China but I haven't personally validated this
